"""Internal package for the sync_folders command."""

from .app import sync_files, sync_folders
from .cli import main, parse_args
from .config import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_MAX_RETRIES,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_RETRY_BATCH_SIZES,
    SyncConfig,
    SyncError,
    build_config,
    ensure_target_directory,
    ensure_output_directory,
    normalize_path,
    positive_int,
    positive_int_tuple,
    validate_directory,
)
from .diff import DifferenceResult, compute_differences, files_differ, iter_source_files
from .logging import Logger
from .report import format_path_list, print_diff_summary, write_diff_report
from .rsync import (
    append_failed_paths,
    batched,
    paths_still_unresolved,
    read_failed_paths,
    refresh_failed_paths,
    retry_batch_size,
    retry_failed_files,
    rsync_command,
    run_batch,
    run_rsync,
    unique_paths,
    write_batch_file,
    write_failed_paths,
)

__all__ = [
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_RETRY_BATCH_SIZES",
    "DifferenceResult",
    "Logger",
    "SyncConfig",
    "SyncError",
    "append_failed_paths",
    "batched",
    "build_config",
    "compute_differences",
    "ensure_target_directory",
    "ensure_output_directory",
    "files_differ",
    "format_path_list",
    "iter_source_files",
    "main",
    "normalize_path",
    "parse_args",
    "paths_still_unresolved",
    "positive_int",
    "positive_int_tuple",
    "print_diff_summary",
    "read_failed_paths",
    "refresh_failed_paths",
    "retry_batch_size",
    "retry_failed_files",
    "rsync_command",
    "run_batch",
    "run_rsync",
    "sync_files",
    "sync_folders",
    "unique_paths",
    "validate_directory",
    "write_batch_file",
    "write_diff_report",
    "write_failed_paths",
]
