#!/usr/bin/env python3
"""Sync missing or changed files from one folder to another."""

from __future__ import annotations

from sync_folders_lib import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_EXCLUDE_PATTERNS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_RETRY_BATCH_SIZES,
    DifferenceResult,
    Logger,
    SyncConfig,
    SyncError,
    append_failed_paths,
    batched,
    build_config,
    clean_exclude_pattern,
    ensure_output_directory,
    compute_differences,
    ensure_target_directory,
    files_differ,
    format_path_list,
    is_excluded_path,
    iter_source_files,
    main,
    normalize_path,
    parse_args,
    path_matches_pattern,
    paths_still_unresolved,
    positive_int,
    positive_int_tuple,
    print_diff_summary,
    read_exclude_patterns,
    read_failed_paths,
    refresh_failed_paths,
    retry_batch_size,
    retry_failed_files,
    rsync_command,
    run_batch,
    run_rsync,
    sync_files,
    sync_folders,
    unique_paths,
    validate_directory,
    write_batch_file,
    write_diff_report,
    write_failed_paths,
)

__all__ = [
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_EXCLUDE_PATTERNS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_RETRY_BATCH_SIZES",
    "DifferenceResult",
    "Logger",
    "SyncConfig",
    "SyncError",
    "append_failed_paths",
    "batched",
    "build_config",
    "clean_exclude_pattern",
    "ensure_output_directory",
    "compute_differences",
    "ensure_target_directory",
    "files_differ",
    "format_path_list",
    "is_excluded_path",
    "iter_source_files",
    "main",
    "normalize_path",
    "parse_args",
    "path_matches_pattern",
    "paths_still_unresolved",
    "positive_int",
    "positive_int_tuple",
    "print_diff_summary",
    "read_exclude_patterns",
    "read_failed_paths",
    "refresh_failed_paths",
    "retry_batch_size",
    "retry_failed_files",
    "rsync_command",
    "run_batch",
    "run_rsync",
    "sync_files",
    "sync_folders",
    "unique_paths",
    "validate_directory",
    "write_batch_file",
    "write_diff_report",
    "write_failed_paths",
]


if __name__ == "__main__":
    raise SystemExit(main())
